### ISSUE TITLE
Avoid redundant data transfomrations

### ISSUE THREAD

**Issue by Tobiaspk** [hussenmi/hto_dnd#2]
DSB normalisation transforms data first to pd.DataFrame, then back to numpy. Propose to skip the dataframe step.

**Comment by hussenmi** [comment]
yeah, good catch! I originally added the compiled it to a dataframe to keep track of the variable names, but not needed now since we're just adding the final result as a layer and the names are stored in the rest of the data object

**Comment by Tobiaspk** [comment]
Great thanks for fixing!
